FROM cf-docker.wangyitu.tech/kdvolder/jdk8

MAINTAINER banchuanyu <banchuanyu@xiaomi.com>
MAINTAINER zhangpeng <zhangpeng@xiaomi.com>

ENV SHEPHER_HOME /usr/shepher
ENV BASE_DIR /usr/shepher

WORKDIR $SHEPHER_HOME

# 复制应用程序和配置文件
COPY ./shepher-web/target/shepher-1.0.jar $SHEPHER_HOME/lib/
COPY ./bin/wait-for-it.sh $SHEPHER_HOME
COPY ./db/init.sql $SHEPHER_HOME
COPY ./conf/* $SHEPHER_HOME/conf/

# 设置环境变量默认值
ENV MYSQL_HOST=host.docker.internal
ENV MYSQL_PORT=3306
ENV MYSQL_DATABASE=shepher
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
ENV JAVA_OPTS=""

## 创建启动脚本
#RUN echo '#!/bin/sh' > $SHEPHER_HOME/start.sh && \
#    echo 'java $JAVA_OPTS -jar lib/shepher-1.0.jar \
#    --spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false \
#    --spring.datasource.username=${MYSQL_USER} \
#    --spring.datasource.password=${MYSQL_PASSWORD} \
#    --spring.config.location=conf/application-base.properties,conf/application-docker.properties \
#    -Djava.ext.dirs=lib' >> $SHEPHER_HOME/start.sh && \
#    chmod +x $SHEPHER_HOME/start.sh
#
## 设置启动命令，使用绝对路径
#CMD ["sh", "/usr/shepher/start.sh"]

# 设置启动命令
CMD sh -c "java $JAVA_OPTS -jar lib/shepher-1.0.jar \
    --spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false \
    --spring.datasource.username=${MYSQL_USER} \
    --spring.datasource.password=${MYSQL_PASSWORD} \
    --spring.config.location=conf/application-base.properties,conf/application-docker.properties \
    -Djava.ext.dirs=lib"

EXPOSE 8089


#docker rmi -f shepher:1.0
# docker build -t shepher:1.0 -f Dockerfile-m1 .



# docker rm -f shepher
# docker run --name shepher -e MYSQL_HOST=host.docker.internal -e MYSQL_PORT=3307 -p 8085:8089 shepher:1.0

# docker run --name shepher \
#   -e MYSQL_HOST=host.docker.internal \
#   -e MYSQL_PORT=3306 \
#   -e MYSQL_DATABASE=shepher \
#   -e MYSQL_USER=root \
#   -e MYSQL_PASSWORD=Wj@1234 \
#   -e JAVA_OPTS="-Xmx512m -Xms256m" \
#   -p 8085:8089 \
#   swr.cn-north-4.myhuaweicloud.com/mewangjun/shepher:1.0